[Settings]
# 模板文件路径， 默认值: config/demo.txt | Template file path, Default value: config/demo.txt
source_file = config/user_demo.txt
# 生成结果文件路径; 默认值: output/result.txt | Generate result file path; Default value: output/result.txt
final_file = output/user_result.txt
# 结果中偏好的 IPv4 接口数量 | Preferred number of IPv4 interfaces in the result
ipv4_num = 10
# 结果中偏好的 IPv6 接口数量 | Preferred number of IPv6 interfaces in the result
ipv6_num = 0
# 生成结果中接口的协议类型，可选值：ipv4、ipv6、全部、all | Protocol type of the interface in the generated result, optional values: ipv4, ipv6, 全部, all
ipv_type = ipv4
# 接口协议类型偏好，优先将该类型的接口排在结果前面，可选值：ipv4、ipv6、自动、auto | Interface protocol type preference, prefer to put this type of interface in front of the result, optional values: ipv4, ipv6, 自动, auto
ipv_type_prefer = ipv4
